#!/bin/sh

#specify the log file with a single argument
if [ $# -ne 1 ]; then
  echo $0: "[log file]"
  exit 1
fi

#check the integrity of command close tags
cat $1 | grep -n . | tr "\n" "\`" | sed "s@</rservr>\`@</rservr>@g" | tr "\`" "\n" | \
  egrep "^[0-9]+:</rservr>" | egrep -v "^[0-9]+:</rservr>($|[0-9]+:<rservr [^<]+>)" | \
  sed -r "s@^[0-9]+:</rservr>@@" | sed -r "s@([^0-9])([0-9]+:)@\1\n\2@g" | grep .

#check the integrity of command open tags
cat $1 | grep -n . | tr "\n" "\`" | sed -r "s@\`([0-9]+:<rservr [^<]+>)@\1@g" | \
  tr "\`" "\n" | egrep "[0-9]+:<rservr [^<]+>$" | \
  egrep -v "^([0-9]+:</rservr>|)[0-9]+:<rservr [^<]+>$" | \
  sed -r "s@^[0-9]+:</rservr>@@" | sed -r "s@[0-9]+:<rservr [^<]+>\$@@" | grep .
