import distutils.core

distutils.core.setup(name = 'rservr', version = '0.1',
    ext_modules = [distutils.core.Extension(name = 'rservr',
        sources = [
        'src/load-all.c',
        'src/command.c',
        'src/client.c',
        'src/log-output.c',
        'src/admin-client.c',
        'src/service-client.c',
        'src/control-client.c',
        'src/resource-client.c',
        'src/monitor-client.c',
        'src/detached-client.c',
        'src/command-queue.c',
        'src/message-queue.c',
        'src/request.c',
        'src/response.c',
        'src/load-plugin.c',
        'src/command-table.c',
        'src/remote-service.c',
        'src/client-timing.c',
        'src/tools.c',
        'src/label-check.c',
        'src/rsvp-dataref-hook.c',
        'src/rsvp-dataref-thread.c',
        'src/rsvp-dataref.c',
        'src/rsvp-netcntl-hook.c',
        'src/rsvp-netcntl.c',
        'src/rsvp-passthru-assist.c',
        'src/rsvp-passthru-hook.c',
        'src/rsvp-passthru.c',
        'src/rsvp-ready-hook.c',
        'src/rsvp-ready.c',
        'src/rsvp-rqconfig-hook.c',
        'src/rsvp-rqconfig-thread.c',
        'src/rsvp-rqconfig.c',
        'src/rsvp-rqsrvc-auto.c',
        'src/rsvp-rqsrvc-hook.c',
        'src/rsvp-rqsrvc.c',
        'src/rsvp-trigger-hook.c',
        'src/rsvp-trigger.c',
        'src/config-parser.c'],
        libraries = ['rservr-client'])])
