.TH "rservr/plugin-dev Directory Reference" 3 "Fri Oct 24 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/plugin-dev Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient-interface\&.hpp\fP"
.br
.ti -1c
.RI "file \fBentry-point\&.h\fP"
.br
.RI "\fIEntry point for plug-in loading\&. \fP"
.ti -1c
.RI "file \fBexternal-command\&.hpp\fP"
.br
.ti -1c
.RI "file \fBheader-macro\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmanual-command\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsource-macro\&.hpp\fP"
.br
.in -1c
