.TH "rservr/plugins Directory Reference" 3 "Sun Oct 26 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/plugins Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrsvp-dataref-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-dataref-thread\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-dataref\&.h\fP"
.br
.RI "\fIData reference transmission command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-netcntl-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-netcntl\&.h\fP"
.br
.RI "\fINetwork connection command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-passthru-assist\&.h\fP"
.br
.RI "\fIAssistance functions for \fBrsvp-passthru\&.h\fP command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-passthru-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-passthru\&.h\fP"
.br
.RI "\fIConnection-reutilizing command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-ready-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-ready\&.h\fP"
.br
.RI "\fIReadiness-reporting command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-rqconfig-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-rqconfig-thread\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-rqconfig\&.h\fP"
.br
.RI "\fISelf-configuration-requesting command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-rqsrvc-auto\&.h\fP"
.br
.RI "\fIAutomation of \fBrsvp-rqsrvc\&.h\fP command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-rqsrvc-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-rqsrvc\&.h\fP"
.br
.RI "\fIRemote-service-registration command plug-in\&. \fP"
.ti -1c
.RI "file \fBrsvp-trigger-hook\&.h\fP"
.br
.ti -1c
.RI "file \fBrsvp-trigger\&.h\fP"
.br
.RI "\fIEvent-triggering command plug-in\&. \fP"
.ti -1c
.RI "file \fBthread-macro\&.h\fP"
.br
.in -1c
