.TH "rservr Directory Reference" 3 "Mon Oct 27 2014" "Version gamma.10" "rservr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapi\fP"
.br
.ti -1c
.RI "directory \fBplugin-dev\fP"
.br
.ti -1c
.RI "directory \fBplugins\fP"
.br
.ti -1c
.RI "directory \fBremote\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig-parser\&.h\fP"
.br
.RI "\fIUniform configuration parsing\&. \fP"
.ti -1c
.RI "file \fBconfig-parser\&.hpp\fP"
.br
.RI "\fIConfiguration shortcuts for C++\&. \fP"
.ti -1c
.RI "file \fBfilter\&.h\fP"
.br
.ti -1c
.RI "file \fBopen-file\&.h\fP"
.br
.RI "\fIProtocol-based file access\&. \fP"
.in -1c
