.TH "config_arguments" 3 "Sun Oct 26 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_arguments \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rservr/config-parser\&.hpp>\fP
.SH "Detailed Description"
.PP 
Storage struct of arguments\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
