.TH "rservr/config-parser.hpp" 3 "Mon Oct 27 2014" "Version gamma.10" "rservr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/config-parser.hpp \- 
.PP
Configuration shortcuts for C++\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBconfig_arguments\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::list< std::string > \fBconfig_arguments_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kevin P\&. Barry 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef std::list<std::string> \fBconfig_arguments_data\fP"
List of configuration arguments\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for rservr from the source code\&.
