.TH "external_buffer" 3 "Fri Oct 24 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
external_buffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rservr/remote/external-buffer\&.hpp>\fP
.SH "Detailed Description"
.PP 
For internal use only\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
