.TH "external_buffer" 3 "Mon Oct 27 2014" "Version gamma.10" "rservr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
external_buffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rservr/remote/external-buffer\&.hpp>\fP
.SH "Detailed Description"
.PP 
For internal use only\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for rservr from the source code\&.
