.TH "incoming_info_data" 3 "Sun Oct 26 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
incoming_info_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rservr/api/message-queue\&.h>\fP
.SH "Detailed Description"
.PP 
For macro and internal use only\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
