.TH "rservr/api/log-output.h" 3 "Sun Oct 26 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/api/log-output.h \- 
.PP
Client log control\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBresult\fP \fBset_program_name\fP (\fBtext_info\fP Name)"
.br
.RI "\fISet the program name\&. \fP"
.ti -1c
.RI "\fBresult\fP \fBset_log_file\fP (\fBtext_info\fP File)"
.br
.RI "\fISet the log file\&. \fP"
.ti -1c
.RI "\fBresult\fP \fBset_log_fd\fP (int File)"
.br
.RI "\fISet the log file\&. \fP"
.ti -1c
.RI "\fBresult\fP \fBhave_log_access\fP (void)"
.br
.RI "\fIDetermine log access\&. \fP"
.ti -1c
.RI "\fBresult\fP \fBset_logging_mode\fP (\fBlogging_mode\fP Mode)"
.br
.RI "\fISet the logging profile\&. \fP"
.ti -1c
.RI "\fBresult\fP \fBset_log_client_name\fP (\fBtext_info\fP Name)"
.br
.RI "\fISet the client's name\&. \fP"
.ti -1c
.RI "\fBresult\fP \fBclient_log_output\fP (\fBlogging_mode\fP Mode, const char *Source, const char *Message)"
.br
.RI "\fIManually log locally\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kevin P\&. Barry This header contains functions used to control the client's automatic logging format\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBresult\fP set_program_name (\fBtext_info\fPName)"
Set the name of the executable used to create the current client\&. This is normally argv[0]\&. This should be the first function called when a client program starts\&. 
.PP
\fBSee also:\fP
.RS 4
\fBinitialize_client\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fIName\fP name of the executable 
.RE
.PP
\fBReturns:\fP
.RS 4
success (true) or failure (false) 
.RE
.PP

.SS "\fBresult\fP set_log_file (\fBtext_info\fPFile)"
Change the file used for automatic client logging\&.
.PP
\fBParameters:\fP
.RS 4
\fIFile\fP name of the new file or device 
.RE
.PP
\fBReturns:\fP
.RS 4
success (true) or failure (false) 
.RE
.PP

.SS "\fBresult\fP set_log_fd (intFile)"
Change the file used for automatic client logging\&. 
.PP
\fBSee also:\fP
.RS 4
\fBset_log_file\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fIFile\fP file descriptor open for writing 
.RE
.PP
\fBReturns:\fP
.RS 4
success (true) or failure (false) 
.RE
.PP

.SS "\fBresult\fP have_log_access (void)"
Determine if the client inherited the server's log file\&.
.PP
\fBReturns:\fP
.RS 4
yes (true) or no (false) 
.RE
.PP

.SS "\fBresult\fP set_logging_mode (\fBlogging_mode\fPMode)"
Change the automatic logging profile of the client\&. 
.PP
\fBSee also:\fP
.RS 4
\fBcommand\&.h\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fIMode\fP logging mode mask 
.RE
.PP
\fBReturns:\fP
.RS 4
success (true) or failure (false) 
.RE
.PP

.SS "\fBresult\fP set_log_client_name (\fBtext_info\fPName)"
Set an alternate name to be used as the client's name\&. This name is only used in the automatic log if the client isn't registered or if the client is registered without a name\&.
.PP
\fBParameters:\fP
.RS 4
\fIName\fP alternate client name 
.RE
.PP
\fBReturns:\fP
.RS 4
success (true) or failure (false) 
.RE
.PP

.SS "\fBresult\fP client_log_output (\fBlogging_mode\fPMode, const char *Source, const char *Message)"
Add a new line of output to the client's log\&.
.PP
\fBParameters:\fP
.RS 4
\fIMode\fP logging mode applicable 
.br
\fISource\fP short name of the source, such as 'local' or 'internal' 
.br
\fIMessage\fP message to be added to the log 
.RE
.PP
\fBReturns:\fP
.RS 4
success (true) or failure (false) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
