.TH "monitor_update_data" 3 "Mon Oct 27 2014" "Version gamma.10" "rservr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monitor_update_data \- 
.PP
Monitor update data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rservr/api/monitor-client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmonitor_event\fP \fBevent_type\fP"
.br
.ti -1c
.RI "\fBinfo_list\fP \fBevent_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Update data from the server based on a specific, monitored event\&. 
.SH "Field Documentation"
.PP 
.SS "\fBmonitor_event\fP monitor_update_data::event_type"
type of event 
.SS "\fBinfo_list\fP monitor_update_data::event_data"
list of data associated with event 

.SH "Author"
.PP 
Generated automatically by Doxygen for rservr from the source code\&.
