.TH "rservr/api/remote-service.h" 3 "Mon Oct 27 2014" "Version gamma.10" "rservr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/api/remote-service.h \- 
.PP
Remote service actions\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kevin P\&. Barry This header contains the interface used by the standard IPC forwarders to monitor connections that remote services rely on\&. This interface isn't currently supported for direct client program use\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for rservr from the source code\&.
