.TH "rservr/plugins/rsvp-dataref.h" 3 "Sun Oct 26 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/plugins/rsvp-dataref.h \- 
.PP
Data reference transmission command plug-in\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrsvp_dataref_load\fP (struct local_commands *Loader)"
.br
.RI "\fILoad the plug-in\&. \fP"
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_dataref_open_reference\fP (\fBtext_info\fP Target, \fBtext_info\fP Location, int Reference, uint8_t Type, uint8_t Mode)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_dataref_change_reference\fP (\fBtext_info\fP Target, \fBtext_info\fP Location, int Reference, uint8_t Type, uint8_t Mode)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_dataref_close_reference\fP (\fBtext_info\fP Target, int Reference)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_dataref_transfer_data\fP (\fBtext_info\fP Target, int Reference, uint8_t Mode, ssize_t Offset, ssize_t Size)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_dataref_alteration_response\fP (\fBmessage_handle\fP Message, int Reference, ssize_t Offset, ssize_t Size)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kevin P\&. Barry 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int rsvp_dataref_load (struct local_commands *Loader)"
Call this in load_all_commands if you're using multiple standard command plug-ins\&. 
.PP
\fBSee also:\fP
.RS 4
\fBload_all_commands\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fILoader\fP command loader provided to load_all_commands 
.RE
.PP
\fBReturns:\fP
.RS 4
success (0) or failure (-1) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_dataref_open_reference (\fBtext_info\fPTarget, \fBtext_info\fPLocation, intReference, uint8_tType, uint8_tMode)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fILocation\fP Location of data (file, port, etc\&.) 
.br
\fIReference\fP Initiator-provided reference value\&. 
.br
\fIType\fP Type of data location used\&. 
.br
\fIMode\fP Open mode flags\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_dataref_change_reference (\fBtext_info\fPTarget, \fBtext_info\fPLocation, intReference, uint8_tType, uint8_tMode)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fILocation\fP Location of data (file, port, etc\&.) 
.br
\fIReference\fP Initiator-provided reference value\&. 
.br
\fIType\fP Type of data location used\&. 
.br
\fIMode\fP Open mode flags\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_dataref_close_reference (\fBtext_info\fPTarget, intReference)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fIReference\fP Initiator-provided reference value\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_dataref_transfer_data (\fBtext_info\fPTarget, intReference, uint8_tMode, ssize_tOffset, ssize_tSize)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fIReference\fP Initiator-provided reference value\&. 
.br
\fIMode\fP Read/write mode flags\&. 
.br
\fIOffset\fP 
.br
\fISize\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_dataref_alteration_response (\fBmessage_handle\fPMessage, intReference, ssize_tOffset, ssize_tSize)"

.PP
\fBParameters:\fP
.RS 4
\fIMessage\fP 
.br
\fIReference\fP Initiator-provided reference value\&. 
.br
\fIOffset\fP 
.br
\fISize\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
