.TH "rservr/plugins/rsvp-ready.h" 3 "Fri Oct 24 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/plugins/rsvp-ready.h \- 
.PP
Readiness-reporting command plug-in\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrsvp_ready_load\fP (struct local_commands *Loader)"
.br
.RI "\fILoad the plug-in\&. \fP"
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_ready_system_ready\fP (\fBtext_info\fP Target, \fBtext_info\fP System)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_ready_system_ready_response\fP (\fBmessage_handle\fP Message, \fBtext_info\fP System)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_ready_system_not_ready\fP (\fBtext_info\fP Target, \fBtext_info\fP System)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_ready_system_not_ready_response\fP (\fBmessage_handle\fP Message, \fBtext_info\fP System)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_ready_system_never_ready\fP (\fBtext_info\fP Target, \fBtext_info\fP System)"
.br
.ti -1c
.RI "\fBcommand_handle\fP \fBrsvp_ready_system_never_ready_response\fP (\fBmessage_handle\fP Message, \fBtext_info\fP System)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kevin P\&. Barry 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int rsvp_ready_load (struct local_commands *Loader)"
Call this in load_all_commands if you're using multiple standard command plug-ins\&. 
.PP
\fBSee also:\fP
.RS 4
\fBload_all_commands\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fILoader\fP command loader provided to load_all_commands 
.RE
.PP
\fBReturns:\fP
.RS 4
success (0) or failure (-1) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_ready_system_ready (\fBtext_info\fPTarget, \fBtext_info\fPSystem)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fISystem\fP system being reported on 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_ready_system_ready_response (\fBmessage_handle\fPMessage, \fBtext_info\fPSystem)"

.PP
\fBParameters:\fP
.RS 4
\fIMessage\fP 
.br
\fISystem\fP system being reported on 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_ready_system_not_ready (\fBtext_info\fPTarget, \fBtext_info\fPSystem)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fISystem\fP system being reported on 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_ready_system_not_ready_response (\fBmessage_handle\fPMessage, \fBtext_info\fPSystem)"

.PP
\fBParameters:\fP
.RS 4
\fIMessage\fP 
.br
\fISystem\fP system being reported on 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_ready_system_never_ready (\fBtext_info\fPTarget, \fBtext_info\fPSystem)"

.PP
\fBParameters:\fP
.RS 4
\fITarget\fP 
.br
\fISystem\fP system being reported on 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SS "\fBcommand_handle\fP rsvp_ready_system_never_ready_response (\fBmessage_handle\fPMessage, \fBtext_info\fPSystem)"

.PP
\fBParameters:\fP
.RS 4
\fIMessage\fP 
.br
\fISystem\fP system being reported on 
.RE
.PP
\fBReturns:\fP
.RS 4
queued command or error (NULL) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
