.TH "rservr/api/timing.h" 3 "Fri Oct 24 2014" "Version gamma.10" "Resourcerver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rservr/api/timing.h \- 
.PP
System timing structures\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Kevin P\&. Barry This header contains the fundamental timing structures used by the server and clients\&. This interface isn't currently supported for direct client program use\&. Timing adjustments should be handled via the server at run-time\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBclient-timing\&.h\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Resourcerver from the source code\&.
