#include <rservr/param.h>

#include "load-all.h"
#include "python-macro.h"


int python_load_param(PyObject *MODULE)
{
#ifdef PARAM_DEBUG_LOG
	LONG_CONSTANT_VAL(PARAM_DEBUG_LOG, 1)
#else
	LONG_CONSTANT_VAL(PARAM_DEBUG_LOG, 0)
#endif


#ifdef PARAM_NEW_SIG
	LONG_CONSTANT(PARAM_NEW_SIG)
#else
	NONE_VALUE(PARAM_NEW_SIG)
#endif


#ifdef PARAM_NO_DAEMON
	LONG_CONSTANT_VAL(PARAM_NO_DAEMON, 1)
#else
	LONG_CONSTANT_VAL(PARAM_NO_DAEMON, 0)
#endif


#ifdef PARAM_NO_SESSION
	LONG_CONSTANT_VAL(PARAM_NO_SESSION, 1)
#else
	LONG_CONSTANT_VAL(PARAM_NO_SESSION, 0)
#endif


#ifdef PARAM_FORK_LOG_MODE
	LONG_CONSTANT(PARAM_FORK_LOG_MODE)
#else
	NONE_VALUE(PARAM_FORK_LOG_MODE)
#endif


#ifdef PARAM_ALLOW_DEBUG_LOOPHOLES
	LONG_CONSTANT_VAL(PARAM_ALLOW_DEBUG_LOOPHOLES, 1)
#else
	LONG_CONSTANT_VAL(PARAM_ALLOW_DEBUG_LOOPHOLES, 0)
#endif


#ifdef PARAM_RSVX_TLS_LOGGING
	LONG_CONSTANT(PARAM_RSVX_TLS_LOGGING)
#else
	NONE_VALUE(PARAM_RSVX_TLS_LOGGING)
#endif


#ifdef PARAM_DEFAULT_LOG_MODE
	LONG_CONSTANT(PARAM_DEFAULT_LOG_MODE)
#else
	NONE_VALUE(PARAM_DEFAULT_LOG_MODE)
#endif


#ifdef PARAM_FILE_CREATE_MODE
	LONG_CONSTANT(PARAM_FILE_CREATE_MODE)
#else
	NONE_VALUE(PARAM_FILE_CREATE_MODE)
#endif


#ifdef PARAM_FILE_CREATE_MASK
	LONG_CONSTANT(PARAM_FILE_CREATE_MASK)
#else
	NONE_VALUE(PARAM_FILE_CREATE_MASK)
#endif


#ifdef PARAM_MAX_INPUT_SECTION
	LONG_CONSTANT(PARAM_MAX_INPUT_SECTION)
#else
	NONE_VALUE(PARAM_MAX_INPUT_SECTION)
#endif


#ifdef PARAM_MAX_HOLDING_INPUT
	LONG_CONSTANT(PARAM_MAX_HOLDING_INPUT)
#else
	NONE_VALUE(PARAM_MAX_HOLDING_INPUT)
#endif


#ifdef PARAM_MAX_COMMAND_DATA
	LONG_CONSTANT(PARAM_MAX_COMMAND_DATA)
#else
	NONE_VALUE(PARAM_MAX_COMMAND_DATA)
#endif


#ifdef PARAM_MAX_TRANSMISSION
	LONG_CONSTANT(PARAM_MAX_TRANSMISSION)
#else
	NONE_VALUE(PARAM_MAX_TRANSMISSION)
#endif


#ifdef PARAM_DEFAULT_FORMAT_BUFFER
	LONG_CONSTANT(PARAM_DEFAULT_FORMAT_BUFFER)
#else
	NONE_VALUE(PARAM_DEFAULT_FORMAT_BUFFER)
#endif


#ifdef PARAM_ENTITY_FILTER
	STRING_CONSTANT(PARAM_ENTITY_FILTER)
#else
	NONE_VALUE(PARAM_ENTITY_FILTER)
#endif


#ifdef PARAM_ADDRESS_FILTER
	STRING_CONSTANT(PARAM_ADDRESS_FILTER)
#else
	NONE_VALUE(PARAM_ADDRESS_FILTER)
#endif


#ifdef PARAM_ENTITY_LIMIT
	LONG_CONSTANT(PARAM_ENTITY_LIMIT)
#else
	NONE_VALUE(PARAM_ENTITY_LIMIT)
#endif


#ifdef PARAM_ADDRESS_LIMIT
	LONG_CONSTANT(PARAM_ADDRESS_LIMIT)
#else
	NONE_VALUE(PARAM_ADDRESS_LIMIT)
#endif


#ifdef PARAM_SCOPE_LIMIT
	LONG_CONSTANT(PARAM_SCOPE_LIMIT)
#else
	NONE_VALUE(PARAM_SCOPE_LIMIT)
#endif


#ifdef PARAM_LOG_TIME_FORMAT
	STRING_CONSTANT(PARAM_LOG_TIME_FORMAT)
#else
	NONE_VALUE(PARAM_LOG_TIME_FORMAT)
#endif


#ifdef PARAM_CACHE_COMMAND_OUTPUT
	LONG_CONSTANT_VAL(PARAM_CACHE_COMMAND_OUTPUT, 1)
#else
	LONG_CONSTANT_VAL(PARAM_CACHE_COMMAND_OUTPUT, 0)
#endif


#ifdef PARAM_IPC_DESCRIPTOR_OFFSET
	LONG_CONSTANT(PARAM_IPC_DESCRIPTOR_OFFSET)
#else
	NONE_VALUE(PARAM_IPC_DESCRIPTOR_OFFSET)
#endif


#ifdef PARAM_ASYM_REMOTE_SERVICES
	LONG_CONSTANT_VAL(PARAM_ASYM_REMOTE_SERVICES, 1)
#else
	LONG_CONSTANT_VAL(PARAM_ASYM_REMOTE_SERVICES, 0)
#endif


#ifdef PARAM_ABSOLUTE_LOCAL_SOCKETS
	LONG_CONSTANT_VAL(PARAM_ABSOLUTE_LOCAL_SOCKETS, 1)
#else
	LONG_CONSTANT_VAL(PARAM_ABSOLUTE_LOCAL_SOCKETS, 0)
#endif


#ifdef PARAM_SERVER_DEFAULT_UNAME
	STRING_CONSTANT(PARAM_SERVER_DEFAULT_UNAME)
#else
	NONE_VALUE(PARAM_SERVER_DEFAULT_UNAME)
#endif


#ifdef PARAM_SERVER_DEFAULT_GNAME
	STRING_CONSTANT(PARAM_SERVER_DEFAULT_GNAME)
#else
	NONE_VALUE(PARAM_SERVER_DEFAULT_GNAME)
#endif


#ifdef PARAM_DEFAULT_PERMISSION
	LONG_CONSTANT(PARAM_DEFAULT_PERMISSION)
#else
	NONE_VALUE(PARAM_DEFAULT_PERMISSION)
#endif


#ifdef PARAM_SERVER_MULTI_LOCK
	LONG_CONSTANT(PARAM_SERVER_MULTI_LOCK)
#else
	NONE_VALUE(PARAM_SERVER_MULTI_LOCK)
#endif


#ifdef PARAM_MAX_CLIENT_ERROR
	LONG_CONSTANT(PARAM_MAX_CLIENT_ERROR)
#else
	NONE_VALUE(PARAM_MAX_CLIENT_ERROR)
#endif


#ifdef PARAM_MAX_CLIENT_INVALID
	LONG_CONSTANT(PARAM_MAX_CLIENT_INVALID)
#else
	NONE_VALUE(PARAM_MAX_CLIENT_INVALID)
#endif


#ifdef PARAM_MAX_CLIENT_COMMANDS
	LONG_CONSTANT(PARAM_MAX_CLIENT_COMMANDS)
#else
	NONE_VALUE(PARAM_MAX_CLIENT_COMMANDS)
#endif


#ifdef PARAM_MAX_COMMANDS
	LONG_CONSTANT(PARAM_MAX_COMMANDS)
#else
	NONE_VALUE(PARAM_MAX_COMMANDS)
#endif


#ifdef PARAM_ALLOW_SERVER_REQUEUE
	LONG_CONSTANT(PARAM_ALLOW_SERVER_REQUEUE)
#else
	NONE_VALUE(PARAM_ALLOW_SERVER_REQUEUE)
#endif


#ifdef PARAM_MAX_CLIENTS
	LONG_CONSTANT(PARAM_MAX_CLIENTS)
#else
	NONE_VALUE(PARAM_MAX_CLIENTS)
#endif


#ifdef PARAM_MAX_SERVICES
	LONG_CONSTANT(PARAM_MAX_SERVICES)
#else
	NONE_VALUE(PARAM_MAX_SERVICES)
#endif


#ifdef PARAM_TIME_PRIORITY_FACTOR
	DOUBLE_CONSTANT(PARAM_TIME_PRIORITY_FACTOR)
#else
	NONE_VALUE(PARAM_TIME_PRIORITY_FACTOR)
#endif


#ifdef PARAM_BULK_EXECUTE_CENTER
	DOUBLE_CONSTANT(PARAM_BULK_EXECUTE_CENTER)
#else
	NONE_VALUE(PARAM_BULK_EXECUTE_CENTER)
#endif


#ifdef PARAM_BULK_EXECUTE_FLOOR
	LONG_CONSTANT(PARAM_BULK_EXECUTE_FLOOR)
#else
	NONE_VALUE(PARAM_BULK_EXECUTE_FLOOR)
#endif


#ifdef PARAM_EXECUTE_HEAP_ORDER
	LONG_CONSTANT(PARAM_EXECUTE_HEAP_ORDER)
#else
	NONE_VALUE(PARAM_EXECUTE_HEAP_ORDER)
#endif


#ifdef PARAM_REQUEUE_PENALTY
	LONG_CONSTANT(PARAM_REQUEUE_PENALTY)
#else
	NONE_VALUE(PARAM_REQUEUE_PENALTY)
#endif


#ifdef PARAM_PENALTY_MAX
	LONG_CONSTANT(PARAM_PENALTY_MAX)
#else
	NONE_VALUE(PARAM_PENALTY_MAX)
#endif


#ifdef PARAM_DETACHED_SOCKET_CHMOD
	LONG_CONSTANT(PARAM_DETACHED_SOCKET_CHMOD)
#else
	NONE_VALUE(PARAM_DETACHED_SOCKET_CHMOD)
#endif


#ifdef PARAM_DEFAULT_MAX_MESSAGES
	LONG_CONSTANT(PARAM_DEFAULT_MAX_MESSAGES)
#else
	NONE_VALUE(PARAM_DEFAULT_MAX_MESSAGES)
#endif


#ifdef PARAM_RELAY_ADDRESS
	STRING_CONSTANT(PARAM_RELAY_ADDRESS)
#else
	NONE_VALUE(PARAM_RELAY_ADDRESS)
#endif


#ifdef PARAM_CONTROLLER_ADDRESS
	STRING_CONSTANT(PARAM_CONTROLLER_ADDRESS)
#else
	NONE_VALUE(PARAM_CONTROLLER_ADDRESS)
#endif


#ifdef PARAM_RELAY_TYPE
	STRING_CONSTANT(PARAM_RELAY_TYPE)
#else
	NONE_VALUE(PARAM_RELAY_TYPE)
#endif


#ifdef PARAM_LOCALRELAY_TYPE
	STRING_CONSTANT(PARAM_LOCALRELAY_TYPE)
#else
	NONE_VALUE(PARAM_LOCALRELAY_TYPE)
#endif


#ifdef PARAM_NETRELAY_TYPE
	STRING_CONSTANT(PARAM_NETRELAY_TYPE)
#else
	NONE_VALUE(PARAM_NETRELAY_TYPE)
#endif


#ifdef PARAM_LOCAL_SERIAL_SEP
	STRING_CONSTANT(PARAM_LOCAL_SERIAL_SEP)
#else
	NONE_VALUE(PARAM_LOCAL_SERIAL_SEP)
#endif


#ifdef PARAM_NET_SERIAL_SEP
	STRING_CONSTANT(PARAM_NET_SERIAL_SEP)
#else
	NONE_VALUE(PARAM_NET_SERIAL_SEP)
#endif


#ifdef PARAM_NET_PORT_SEP
	STRING_CONSTANT(PARAM_NET_PORT_SEP)
#else
	NONE_VALUE(PARAM_NET_PORT_SEP)
#endif


#ifdef PARAM_FORWARD_MAX_WAITING
	LONG_CONSTANT(PARAM_FORWARD_MAX_WAITING)
#else
	NONE_VALUE(PARAM_FORWARD_MAX_WAITING)
#endif


#ifdef PARAM_MAX_FORWARD_ERROR
	LONG_CONSTANT(PARAM_MAX_FORWARD_ERROR)
#else
	NONE_VALUE(PARAM_MAX_FORWARD_ERROR)
#endif


#ifdef PARAM_FORCE_SOCKET_AUTHORIZE
	LONG_CONSTANT_VAL(PARAM_FORCE_SOCKET_AUTHORIZE, 1)
#else
	LONG_CONSTANT_VAL(PARAM_FORCE_SOCKET_AUTHORIZE, 0)
#endif


#ifdef PARAM_SELF_TRUSTING_FORWARDER
	LONG_CONSTANT_VAL(PARAM_SELF_TRUSTING_FORWARDER, 1)
#else
	LONG_CONSTANT_VAL(PARAM_SELF_TRUSTING_FORWARDER, 0)
#endif


#ifdef PARAM_TERMINAL_NAME
	STRING_CONSTANT(PARAM_TERMINAL_NAME)
#else
	NONE_VALUE(PARAM_TERMINAL_NAME)
#endif


#ifdef PARAM_ECHO_TYPE
	STRING_CONSTANT(PARAM_ECHO_TYPE)
#else
	NONE_VALUE(PARAM_ECHO_TYPE)
#endif


#ifdef PARAM_MESSAGE_PAUSE_THRESHOLD
	DOUBLE_CONSTANT(PARAM_MESSAGE_PAUSE_THRESHOLD)
#else
	NONE_VALUE(PARAM_MESSAGE_PAUSE_THRESHOLD)
#endif


#ifdef PARAM_MESSAGE_PAUSE_RESTORE
	DOUBLE_CONSTANT(PARAM_MESSAGE_PAUSE_RESTORE)
#else
	NONE_VALUE(PARAM_MESSAGE_PAUSE_RESTORE)
#endif


#ifdef PARAM_MESSAGE_PAUSE_TIMEOUT
	DOUBLE_CONSTANT(PARAM_MESSAGE_PAUSE_TIMEOUT)
#else
	NONE_VALUE(PARAM_MESSAGE_PAUSE_TIMEOUT)
#endif


#ifdef PARAM_BYPASS_LENGTH_MAX
	LONG_CONSTANT(PARAM_BYPASS_LENGTH_MAX)
#else
	NONE_VALUE(PARAM_BYPASS_LENGTH_MAX)
#endif


#ifdef PARAM_BYPASS_SIZE_MAX
	LONG_CONSTANT(PARAM_BYPASS_SIZE_MAX)
#else
	NONE_VALUE(PARAM_BYPASS_SIZE_MAX)
#endif


#ifdef PARAM_DISABLE_REMOTE_RECEIPT
	LONG_CONSTANT_VAL(PARAM_DISABLE_REMOTE_RECEIPT, 1)
#else
	LONG_CONSTANT_VAL(PARAM_DISABLE_REMOTE_RECEIPT, 0)
#endif


#ifdef PARAM_RSERVRD_TABLE
	STRING_CONSTANT(PARAM_RSERVRD_TABLE)
#else
	NONE_VALUE(PARAM_RSERVRD_TABLE)
#endif


#ifdef PARAM_RSERVRD_MAX_WAITING
	LONG_CONSTANT(PARAM_RSERVRD_MAX_WAITING)
#else
	NONE_VALUE(PARAM_RSERVRD_MAX_WAITING)
#endif


#ifdef PARAM_RSERVRD_TARGET_REGEX
	LONG_CONSTANT_VAL(PARAM_RSERVRD_TARGET_REGEX, 1)
#else
	LONG_CONSTANT_VAL(PARAM_RSERVRD_TARGET_REGEX, 0)
#endif


#ifdef PARAM_FILTER_OUTGOING
	CHAR_CONSTANT(PARAM_FILTER_OUTGOING)
#else
	NONE_VALUE(PARAM_FILTER_OUTGOING)
#endif


#ifdef PARAM_FILTER_INCOMING
	CHAR_CONSTANT(PARAM_FILTER_INCOMING)
#else
	NONE_VALUE(PARAM_FILTER_INCOMING)
#endif


#ifdef PARAM_FILTER_ALL
	CHAR_CONSTANT(PARAM_FILTER_ALL)
#else
	NONE_VALUE(PARAM_FILTER_ALL)
#endif


#ifdef PARAM_FILTER_NONE
	CHAR_CONSTANT(PARAM_FILTER_NONE)
#else
	NONE_VALUE(PARAM_FILTER_NONE)
#endif


	return 1;
}
